version: "3"

services:
  camis:
    build:
      context: .
      dockerfile: ./camis/Dockerfile
    image: ${DOCKER_REGISTRY}/wanderinglabs/scraper-camis

  recreation_gov:
    build:
      context: .
      dockerfile: ./recreation_gov/Dockerfile
    image: ${DOCKER_REGISTRY}/wanderinglabs/scraper-recreation-gov

  reserve_america:
    build:
      context: .
      dockerfile: ./reserve_america/Dockerfile
    image: ${DOCKER_REGISTRY}/wanderinglabs/scraper-reserve-america

  reserve_ca:
    build:
      context: .
      dockerfile: ./reserve_ca/Dockerfile
    image: ${DOCKER_REGISTRY}/wanderinglabs/scraper-reserve-ca
