version: "3"

services:
  camis:
    build:
      context: .
      dockerfile: ./camis/Dockerfile
    image: ${DOCKER_REGISTRY}/wanderinglabs/scraper-camis

  pinellas-county:
    build:
      context: .
      dockerfile: ./pinellas_county/Dockerfile
    image: ${DOCKER_REGISTRY}/wanderinglabs/scraper-pinellas-county

  recreation-gov:
    build:
      context: .
      dockerfile: ./recreation_gov/Dockerfile
    image: ${DOCKER_REGISTRY}/wanderinglabs/scraper-recreation-gov

  reserve-america:
    build:
      context: .
      dockerfile: ./reserve_america/Dockerfile
    image: ${DOCKER_REGISTRY}/wanderinglabs/scraper-reserve-america

  reserve-ca:
    build:
      context: .
      dockerfile: ./reserve_ca/Dockerfile
    image: ${DOCKER_REGISTRY}/wanderinglabs/scraper-reserve-ca
